name: renv sync check
on: [push, pull_request]
jobs:
  renv-sync:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      RENV_CONFIG_REPOS_OVERRIDE: https://cran.r-project.org
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/renv
            ~/.cache/R/renv
          key: renv-${{ runner.os }}-${{ hashFiles('renv.lock') }}
          restore-keys: renv-${{ runner.os }}-
      - run: Rscript -e 'if (!"renv"%in% rownames(installed.packages())) install.packages("renv")'
      - run: Rscript -e 'renv::restore(prompt=FALSE)'
      - run: Rscript -e 'st<-capture.output(renv::status()); cat(paste(st,collapse="\n"),"\n"); quit(status=any(grepl("inconsistent state",st,ignore.case=TRUE)))'
