name: renv sync check

on: [push, pull_request]

jobs:
  renv-sync:
    runs-on: ubuntu-latest

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      RENV_CONFIG_REPOS_OVERRIDE: https://cran.r-project.org

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # System libraries needed by common R packages (curl, xml2, openssl, git2r, etc.)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            libjpeg-dev libpng-dev libtiff5-dev \
            libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev \
            libx11-dev libxt-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Cache renv packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/renv
            ~/.cache/R/renv
          key: renv-${{ runner.os }}-${{ hashFiles('renv.lock') }}
          restore-keys: |
            renv-${{ runner.os }}-

      - name: Install renv
        run: Rscript -e 'if (!"renv" %in% rownames(installed.packages())) install.packages("renv")'

      - name: Restore project library from lockfile
        run: Rscript -e 'renv::restore(prompt = FALSE)'

      - name: Verify project is synchronized
        run: |
          Rscript -e 'st <- capture.output(renv::status()); cat(paste(st, collapse = "\n"), "\n"); quit(status = any(grepl("inconsistent state", st, ignore.case = TRUE)))'

